### ISSUE TITLE
No TARGET is selected error with KOS

### ISSUE THREAD

**Issue by KrakenAU** [pmborg/SpaceX-RO-Falcons#1]
Here is the error screenshot. I have the latest scripts and files. I hope you can help.

https://gyazo.com/83cbbe94b4ac283e3d1fb859e373e2ca

**Comment by pmborg** [comment]
Hello, can you confirm that this is fixed?
Thx

**Comment by KrakenAU** [comment]
Hi, I got it fixed but now when the booster tries to boostback to land it doesn't stop. Maybe can you do a video on how to set up all the landing sites and stuff

**Comment by pmborg** [comment]
I checked twice, and saved a video the landing is working normally as expected:
https://www.youtube.com/watch?v=JO0yJys-HNg

Load the saved file:
KSP1-10-DEMO-BASE-DroneShip1-2-LZ1-2

Which is the default load demo for F9 flights, for KSP 1.10 ou KSP1.11

**Comment by KrakenAU** [comment]
I used this and it worked fine but now it says that it cant target its self with the SN-9 and with the SN booster it just targets the starship. I don't know whats happening but I will mess around to try fix it

**Comment by pmborg** [comment]
Which official **load file** are you testing now?
https://github.com/pmborg/SpaceX-RO-Falcons/tree/main/saves/InterStar

Please, check my latest commit, it should fix this error once for all.
