### ISSUE TITLE
Dependency installer script and Linux

### ISSUE THREAD

**Issue by stuffnex** [pmborg/SpaceX-RO-Falcons#2]
Hello!
Firstly, thanks for your remarkable work.

**Issue is:**
Script > RealFalcons-Install-For_KSP_1.12.3-All_Dependencies.bat don't run on Linux.

**Kind request:**
While you guys find convenient to add a script for linux systems, could you post the full list of dependencies for manual install?

Thanks for your time.

**Comment by pmborg** [comment]
Hello,
Making a script for Linux is out of my scope and goals, but just open that file with a notepad/vi or similar:
RealFalcons-Install-For_KSP_1.12.3-All_Dependencies.bat

All the logic is there just be just straightforward, just replicate what is writen there manually.
